import keyboard as kbd # importing keyboard module
import time
string = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis, dolor et euismod dictum, enim mauris aliquam arcu, at pretium justo mi ut lacus. Fusce leo risus, dictum sed est ac, auctor feugiat metus. Ut a tortor in nulla mattis dictum ut in ante. Aliquam erat volutpat. In in ex ante. Aenean scelerisque risus ut neque dapibus, a sollicitudin odio elementum. Donec a egestas ante. Nunc non laoreet nisi. Sed quis odio nec ipsum sagittis rutrum at ut augue. Pellentesque at dui iaculis, malesuada lorem fringilla, gravida orci. In ut tincidunt nibh.

In hac habitasse platea dictumst. Ut dictum odio mauris, eu eleifend sem dapibus tincidunt. Aliquam vitae nulla vehicula, commodo ipsum in, faucibus metus. Proin vel elit ut augue sagittis iaculis at sit amet orci. Suspendisse id mi et leo malesuada mollis vitae at nunc. Nam nisl neque, luctus nec laoreet nec, sagittis nec dolor. Aenean porta tempor lacus, at pharetra arcu fringilla eget. Proin at semper neque, varius mollis augue. Sed quis finibus augue. Aliquam nec euismod lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent sollicitudin cursus ipsum pharetra venenatis. Donec auctor ac ex a sagittis.

Donec volutpat sapien venenatis tellus viverra vestibulum. Donec felis magna, dictum et augue non, ultricies sollicitudin lorem. Cras efficitur arcu sit amet luctus feugiat. Phasellus ex leo, sodales eget accumsan vitae, sagittis sit amet lectus. Vestibulum eleifend libero ut commodo feugiat. Cras pharetra sem tincidunt, faucibus ligula non, facilisis tellus. Quisque maximus sodales vulputate. Mauris sodales ut diam id gravida. Vestibulum mattis, ligula eu iaculis hendrerit, massa diam dignissim justo, in faucibus libero mauris sed arcu. Proin mattis interdum neque, eget aliquet nibh faucibus a.

Praesent velit nisl, maximus cursus pharetra id, fermentum ac ipsum. Aenean eleifend enim metus, at accumsan nulla bibendum in. Nullam eu porta nibh, tristique rhoncus dui. Nullam suscipit faucibus lectus, at consequat lacus iaculis lacinia. Aliquam fringilla, quam feugiat semper iaculis, metus risus bibendum dui, ac rutrum felis sem sed velit. In facilisis blandit leo eu malesuada. Cras tempus purus odio, eget iaculis metus cursus at. Sed pulvinar eros et ex molestie, vitae cursus metus mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In at ligula dui. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Fusce tristique ipsum erat, non dapibus risus maximus et. Nam sit amet velit aliquet, luctus nulla eget, sodales diam. Curabitur egestas erat vitae augue efficitur molestie. Vestibulum rhoncus fringilla nibh semper finibus. Integer dolor nibh, vehicula eget sagittis ac, egestas eleifend sem. Vivamus ultricies pharetra feugiat. Nam at nisl eget est tristique gravida vel cursus nulla. Quisque non est non nisi accumsan euismod. Aenean eget sollicitudin urna, a dapibus lacus. In dictum justo quis justo eleifend blandit. Phasellus malesuada augue sit amet urna efficitur pharetra.

Phasellus sollicitudin elit eu lectus hendrerit, vel luctus erat faucibus. Fusce leo magna, gravida quis elit id, interdum pharetra eros. Praesent quis eros varius, tristique ex eu, convallis nisi. Donec scelerisque metus non consequat rutrum. Praesent rhoncus ante elit, aliquam lacinia ante tincidunt id. Suspendisse ipsum mi, lobortis sed lacus eu, tincidunt dignissim enim. Fusce vitae lectus sit amet nisi porttitor blandit. Fusce sollicitudin, dolor sed volutpat volutpat, risus purus placerat mi, in bibendum quam nisi vel metus. Quisque ornare ac lacus sit amet elementum. Morbi condimentum purus libero, ac lobortis dolor pellentesque id. Duis aliquet sed elit sed dictum. Nunc condimentum tempor ligula, sed dapibus purus euismod sed. Duis neque magna, commodo ac ultricies ut, pulvinar non nulla. Ut nulla ipsum, dapibus at mauris a, blandit finibus mauris.

Mauris sollicitudin mattis ligula eget mollis. Ut finibus commodo tincidunt. Nullam ut nulla vestibulum neque sollicitudin porta eu vel libero. Vestibulum tincidunt neque nec convallis lobortis. Fusce ac convallis ante. Nullam id dapibus sapien. Nunc arcu dolor, porttitor eu quam eget, ornare eleifend ex. Quisque eget nibh velit. Phasellus placerat libero in laoreet vulputate. Etiam malesuada velit libero, id auctor libero mollis sed. Quisque eleifend tincidunt porttitor. Sed dolor sem, gravida sit amet ante eget, pellentesque suscipit sapien. Vivamus lacinia lacus risus, quis convallis magna molestie et.

Suspendisse in diam suscipit, porta tortor sit amet, suscipit dui. Donec eleifend fringilla metus vitae semper. Curabitur aliquet sollicitudin risus, vel finibus orci. Curabitur eleifend quam non iaculis lacinia. In semper tellus vel mauris imperdiet, tempor dictum turpis auctor. Aliquam rhoncus est vitae diam auctor tempor. In a cursus lacus. Integer varius urna tincidunt ante maximus lobortis. Ut convallis aliquam quam, nec consequat lacus. Nunc tristique euismod dictum.

Pellentesque nec libero tristique, sodales nunc eu, vulputate justo. Donec ac urna quis purus placerat lobortis quis vel dolor. Vivamus rutrum vitae enim egestas hendrerit. Vivamus tristique et lacus nec feugiat. Mauris ullamcorper nibh vel justo elementum, et porttitor justo placerat. Donec ultricies, sem quis pharetra cursus, neque metus tincidunt libero, sed ornare felis tellus ut arcu. Quisque vitae ante maximus, varius orci vitae, tincidunt odio. Phasellus dapibus tempor leo, et sodales turpis dictum non. Phasellus in neque lorem.

Fusce tellus eros, egestas gravida mollis quis, porttitor ultrices lorem. Mauris sit amet gravida nisi, et commodo quam. Proin vitae neque cursus arcu tristique ultricies sed vel ante. Donec vitae aliquet risus. Pellentesque tincidunt augue vitae neque accumsan eleifend. Mauris nec est ipsum. Ut diam nulla, fermentum sit amet efficitur sed, fermentum sed massa. Phasellus aliquet lorem sed dolor ornare, at dignissim eros aliquam. Aliquam pulvinar enim erat, vitae finibus purus imperdiet vel. Quisque efficitur ornare vestibulum. Quisque maximus dolor quis sollicitudin ultricies. Praesent eros ligula, accumsan ac interdum at, rhoncus sit amet eros. Proin ultricies nisi nec ligula aliquam, nec semper elit vestibulum.

Vestibulum placerat vitae ipsum et ornare. Integer finibus at enim at posuere. Cras luctus velit dui, at tempor felis pellentesque sed. Fusce porttitor convallis metus, id condimentum lectus luctus nec. In sed nulla porta, gravida nisl non, congue lacus. Fusce pellentesque, urna ut scelerisque rhoncus, tortor diam malesuada felis, eget fringilla tortor magna et tellus. Aenean viverra a lacus scelerisque placerat. Cras et ligula quis ipsum varius blandit. Proin id arcu ut urna vestibulum eleifend et quis felis. Proin nisi odio, vehicula et varius et, venenatis sed eros. Morbi congue diam a magna accumsan, eu auctor nisl malesuada. Curabitur non velit et tortor dictum porttitor.

Donec venenatis enim ligula, sit amet viverra leo suscipit eget. Nulla facilisi. Quisque blandit vulputate enim, vitae lacinia lacus luctus non. Vivamus semper felis vehicula libero posuere lacinia. Donec finibus ut justo ac consequat. In consequat orci ligula. Praesent ac ullamcorper enim, nec lobortis massa. Curabitur ante ligula, gravida et dictum et, auctor eu mi. Vestibulum non aliquam lacus.

Vivamus pharetra ante a dui luctus pellentesque. Donec dictum in ligula ut auctor. Maecenas eu justo sed felis gravida rhoncus consequat a lacus. Pellentesque pharetra lectus eget augue ultricies, nec luctus quam convallis. Nunc dolor libero, iaculis sed imperdiet pretium, condimentum lacinia nunc. Nunc sollicitudin ex ipsum, nec pulvinar arcu fermentum a. Sed laoreet accumsan mi, et fringilla velit facilisis a. Donec nec augue ex. Praesent ut quam a tortor vestibulum vehicula eget a ante. Mauris sodales neque eu dui posuere lobortis. Integer tincidunt, tortor quis convallis porta, erat odio ultricies libero, vitae tempor neque purus ut elit. Pellentesque id est volutpat, lobortis est nec, consequat lectus. Ut faucibus, mauris vel vestibulum congue, sapien sapien condimentum lacus, ut condimentum tellus metus eget est. Nulla facilisi.

Quisque condimentum nibh nibh, eget convallis eros malesuada a. Integer dapibus quam in velit porttitor congue eget nec eros. Maecenas erat lectus, accumsan eu sapien eget, varius convallis ligula. Aliquam a massa at sem fringilla pellentesque a ac nisl. Mauris eu massa faucibus, blandit tellus eu, iaculis nulla. Quisque lacus nisl, congue ultrices velit nec, laoreet ultricies diam. Curabitur sit amet elit mauris. Nulla vel ligula dolor. Nam venenatis gravida cursus. Proin cursus risus tristique, lobortis elit id, tempus dolor. Suspendisse ornare tellus ac nisl ornare elementum.

Suspendisse vulputate massa vehicula urna sagittis, suscipit tincidunt ipsum iaculis. Aliquam non elit sem. Nullam tempus mi eu libero tristique malesuada. Duis condimentum, magna in placerat blandit, nisi felis bibendum nunc, eget mattis lorem orci a felis. Fusce suscipit malesuada enim ac ultricies. Etiam eleifend augue velit, id varius velit interdum eu. In tempus viverra porta. Praesent libero enim, bibendum a ipsum sed, condimentum rhoncus lorem. Nunc gravida volutpat ornare.

Pellentesque luctus, magna in accumsan vestibulum, ante tortor varius nunc, vitae suscipit erat erat eu velit. Nulla et suscipit massa. Sed auctor convallis dictum. Etiam pulvinar justo vel orci auctor, vitae sagittis est ultrices. Praesent egestas justo eget est suscipit rutrum. Vestibulum ac suscipit odio. Vestibulum leo magna, feugiat tempus nisl et, malesuada egestas purus. Vivamus sed convallis lacus.

Curabitur ac rhoncus ligula. Sed ut arcu vel libero aliquet blandit ac at lectus. Duis efficitur, magna rutrum elementum elementum, dui ante pretium arcu, ullamcorper auctor metus mi et arcu. Aenean pharetra at leo sed aliquam. Praesent viverra augue eget nisi convallis, ut ultrices augue rhoncus. Pellentesque luctus dapibus arcu non venenatis. Nulla suscipit magna vitae accumsan interdum. Nunc in tincidunt metus. Vivamus et facilisis lacus, id sodales orci. Suspendisse lacinia felis nisi, in bibendum nisl semper quis. Mauris euismod, nibh vel mollis vulputate, nunc eros mollis elit, at molestie elit odio ut enim. Ut euismod diam turpis, sed ullamcorper urna hendrerit at. Proin ut porta purus, vel tincidunt nisi. Phasellus aliquet tincidunt sagittis. Donec massa lacus, convallis eu dolor sed, tempor scelerisque enim.

Aliquam a ultricies augue. Maecenas in turpis felis. Donec varius ultrices mi, quis eleifend lorem efficitur non. Nullam id mi non enim commodo viverra. Aenean eros libero, pulvinar vitae euismod id, molestie in magna. Sed pulvinar venenatis mi, auctor ultrices ex ultrices eu. Pellentesque egestas semper dui, quis rutrum velit. Morbi efficitur, velit sit amet posuere blandit, odio turpis aliquet purus, eu fringilla lectus neque eget ante. Nulla hendrerit euismod neque et convallis. Donec sem velit, scelerisque at rutrum ac, auctor nec turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam placerat interdum tortor, ultrices ullamcorper tellus fringilla vel.

Maecenas lobortis scelerisque dolor eget ornare. Nullam euismod sodales ipsum. Donec nec mauris diam. Quisque at velit sed quam eleifend fringilla eget nec felis. Sed feugiat sem ante, vitae lacinia lorem hendrerit eget. Integer ac efficitur nunc, quis lobortis dui. Aenean justo nunc, gravida ut nisl non, vestibulum aliquam felis. Curabitur viverra mollis nisi, ac pellentesque nunc. Curabitur mauris magna, egestas eget pellentesque vitae, commodo at lectus. Nulla facilisi. Ut sed elit nunc.

Integer nisl massa, fermentum rutrum enim vitae, ullamcorper tincidunt turpis. In hac habitasse platea dictumst. Etiam tempor accumsan tempor. Ut tincidunt purus in enim auctor, ac auctor risus ultrices. Nam facilisis nulla nec tempus consectetur. Etiam sit amet fermentum sapien. Curabitur sem lectus, auctor id mi elementum, semper venenatis urna. Nam luctus tellus tellus, ut porta sapien tincidunt in. Sed quis fermentum ligula. In ornare dapibus est, eget vulputate sapien elementum in. Sed tincidunt porttitor felis eget ullamcorper. Ut at quam id justo viverra scelerisque non non orci. Phasellus porttitor vel felis vel gravida. Quisque vestibulum hendrerit eros et dignissim. Sed id augue efficitur, condimentum tellus sodales, gravida erat. Praesent sed sapien faucibus, fringilla ligula eu, ultrices lorem.

Quisque bibendum ultricies tincidunt. Donec lobortis massa eget suscipit interdum. Etiam eu nunc a massa eleifend tempor. Integer a nisi quis lectus mattis eleifend in vel nisi. Aliquam non est eu libero varius fringilla non vel neque. Nullam id facilisis nulla. Maecenas nec tristique magna. Ut lacinia nibh eget sagittis sodales. Nulla sed lectus vitae nisl aliquam viverra. Proin fermentum dui rutrum, elementum tellus vitae, posuere lorem.

Quisque mattis aliquet aliquet. In et mauris maximus, pulvinar nunc at, pulvinar ligula. Pellentesque aliquet, orci vitae pharetra tristique, nisl tortor convallis leo, ut laoreet libero enim quis ex. Maecenas dolor est, faucibus in porta et, scelerisque et diam. Fusce rhoncus pretium dolor, a porttitor nisl convallis in. Ut molestie arcu non risus porta, eu egestas nibh eleifend. Pellentesque congue ut mi vitae iaculis. Duis sollicitudin lacus id feugiat ullamcorper. Suspendisse potenti. Curabitur nisl arcu, suscipit eu lectus vel, tristique finibus felis.

Morbi est ipsum, cursus sed dignissim eget, pulvinar in tortor. Aliquam erat volutpat. Nullam porttitor ut leo a posuere. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec vitae dolor non lorem auctor lacinia non et mauris. Fusce quis facilisis orci, id laoreet felis. Donec eget consectetur quam. Fusce mattis dui cursus ante laoreet auctor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce posuere ultricies nisi ac vestibulum. Duis dictum ultrices odio, et pellentesque felis malesuada quis. Quisque ut lacus sed turpis tincidunt vulputate vitae nec lorem. Aliquam sed ex vitae justo finibus dictum nec vel risus. In nec convallis mi, eget pharetra metus.

Nam vulputate rutrum nisl, in tempus lacus lacinia sit amet. Mauris facilisis ut ligula vel tincidunt. Praesent lacinia scelerisque lectus, eu ultricies leo. Phasellus fringilla sollicitudin lectus non bibendum. Cras eu fermentum velit. Nulla sit amet tempor elit. Morbi ullamcorper ipsum hendrerit dapibus rutrum. Maecenas ipsum neque, porttitor a justo in, malesuada porta enim. Pellentesque pharetra gravida rhoncus. Morbi finibus vulputate nunc. Curabitur sed tristique lorem, non pharetra metus. Sed lobortis tempus mollis. Aliquam sem sem, porta eget bibendum vestibulum, lacinia et velit. Aliquam pellentesque massa quis condimentum aliquam.

In sollicitudin ac metus non porta. Cras at luctus felis. Nam id tempor eros, ac facilisis odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent posuere blandit urna, nec fermentum metus vulputate vel. Nam dictum aliquam risus, ut sagittis dui tincidunt sit amet. Integer nec mauris eu sem elementum condimentum id ac lacus. Vivamus id imperdiet magna. Vestibulum sagittis justo euismod orci eleifend, a vehicula enim molestie. Duis varius enim quis dapibus tristique. Aliquam eleifend gravida nulla, at tempor elit bibendum a. Etiam urna lorem, auctor efficitur mauris eget, luctus pulvinar velit. Suspendisse potenti. Vestibulum sodales lacinia varius. Nulla porttitor arcu dui, a rhoncus nibh imperdiet nec. Cras lacinia pellentesque maximus.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed aliquam, orci sit amet luctus fringilla, turpis metus pulvinar leo, nec tristique tortor quam at turpis. Aenean consequat augue sed magna tincidunt, vulputate ultrices urna fermentum. Etiam justo metus, scelerisque porttitor euismod in, lobortis et leo. Quisque tortor lacus, congue et porttitor in, ultrices ut nunc. Vivamus tincidunt purus eleifend lacus tincidunt, quis posuere orci convallis. Phasellus semper ligula sit amet tellus maximus euismod. Quisque gravida arcu ligula, at mollis quam ultricies eget. Nam a erat nibh.

Pellentesque sit amet congue leo. Curabitur et commodo mi, vel luctus tellus. In sed quam posuere, scelerisque diam eget, elementum turpis. Ut gravida laoreet erat. Quisque nulla risus, gravida eu dui eu, imperdiet lacinia ligula. Donec euismod tempor diam, non viverra nunc rhoncus eget. Quisque vulputate et quam a tincidunt. Pellentesque varius convallis leo, gravida tristique lacus finibus non.

In urna metus, condimentum quis ante eu, luctus vulputate nibh. Integer lobortis sed massa sit amet placerat. Phasellus aliquet viverra scelerisque. In lobortis auctor enim. Curabitur convallis arcu ut faucibus vulputate. Nullam non ipsum eu metus mollis pellentesque. Donec tristique gravida ipsum, ut tincidunt sem dictum sed. Vestibulum accumsan ligula in sem fringilla, id tincidunt ex pretium. Sed viverra et ipsum ut rhoncus. Nam bibendum sed mauris ac lobortis.

Fusce semper convallis felis, vel posuere ex sodales sed. Praesent mi urna, interdum et pellentesque ut, consectetur sit amet dui. Nunc aliquam eu dui a commodo. Morbi ornare, sem vitae convallis pretium, ligula risus feugiat nisi, eget ultricies arcu elit non tortor. Mauris eleifend, risus eu rhoncus commodo, tortor felis viverra risus, volutpat luctus purus lorem eu lacus. Donec maximus neque id malesuada porttitor. Morbi sit amet nulla tincidunt, ullamcorper est nec, sagittis libero. Nullam euismod risus eget neque vehicula luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Nam sed dolor et sapien efficitur elementum. Vestibulum pellentesque fermentum orci, et placerat dolor finibus in. Praesent euismod finibus sapien ut fringilla. Nulla fringilla ligula diam, finibus bibendum purus feugiat a. In commodo, urna vitae placerat posuere, libero arcu ullamcorper felis, sit amet placerat arcu quam at ipsum. Nulla diam sem, posuere ac varius a, tincidunt in orci. Suspendisse ac risus rhoncus, pulvinar turpis sit amet, ornare augue.

Pellentesque ut purus suscipit, accumsan dolor ut, vestibulum ipsum. Curabitur imperdiet faucibus consequat. Nullam gravida sapien metus, at tincidunt erat pretium a. Vestibulum sollicitudin blandit nulla vitae volutpat. Sed mattis faucibus est at laoreet. Mauris vitae eleifend lorem. Vivamus efficitur efficitur maximus. Fusce in nisl lacus.

Integer pharetra posuere posuere. Duis lectus lorem, convallis scelerisque pellentesque a, porttitor in magna. Ut porttitor mattis ligula vel pretium. Curabitur convallis condimentum interdum. Vivamus at massa sit amet tellus dapibus accumsan. Morbi blandit dolor sed tortor venenatis tempor. Donec fermentum velit ante, at tincidunt dolor egestas eu. Vestibulum feugiat volutpat nibh, non finibus enim euismod et. Nunc et lacus est. Interdum et malesuada fames ac ante ipsum primis in faucibus.

In erat risus, placerat id convallis et, suscipit sit amet enim. Nam dapibus eget lorem sed aliquam. Fusce in molestie dolor, eu ornare libero. Maecenas a quam mi. Maecenas in imperdiet urna, at vehicula leo. In placerat risus vel neque cursus tempus. Curabitur sed eros eget ipsum finibus posuere. Quisque quis dictum massa.

Nullam bibendum felis est, ultricies pharetra lacus mollis vitae. Nunc finibus finibus feugiat. Pellentesque vitae venenatis metus, blandit molestie augue. Donec a risus varius, congue eros sed, suscipit massa. Curabitur a purus urna. Cras fermentum rutrum arcu non eleifend. Suspendisse in volutpat est. Integer vitae aliquet nulla. Nunc sed magna rutrum, condimentum urna sed, faucibus dolor.

Fusce et volutpat eros. In posuere dui massa. Phasellus tempus eros justo, at ornare velit elementum et. Ut eget nibh vulputate, suscipit arcu sit amet, porttitor lacus. Donec malesuada augue ante, eget efficitur nulla porttitor vel. Sed at urna ac velit hendrerit luctus. Donec malesuada sit amet ipsum in blandit. Ut rutrum libero mauris, ut posuere neque malesuada id. Vivamus accumsan volutpat justo ut interdum. Praesent sed consectetur nisi, eu gravida est. Nam ut elit velit.

Integer eget sagittis lorem. Donec est turpis, vulputate non lectus quis, convallis egestas justo. Morbi vulputate maximus facilisis. Nulla eleifend turpis vitae porta egestas. In purus arcu, suscipit eget pellentesque et, suscipit non augue. Donec vel leo lacinia felis suscipit venenatis malesuada non tortor. Ut ullamcorper id nunc in finibus. Integer mattis massa quis nisl imperdiet faucibus. Duis consectetur finibus congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Quisque placerat tellus et ipsum porttitor blandit. Curabitur suscipit velit sed nisl commodo venenatis consectetur vitae ex. Vestibulum commodo metus mi, et tincidunt velit placerat efficitur. Aliquam consectetur augue sed neque pellentesque semper. Vivamus efficitur sed ex quis porta. Aliquam semper ut ex quis mattis.

Cras nec consequat tellus. Fusce quis tincidunt magna. Pellentesque nunc felis, sodales at tempus eget, elementum ac leo. Morbi tristique faucibus elit quis aliquam. Nunc pellentesque molestie justo in porttitor. Morbi sit amet blandit risus. Nam non volutpat ante. Suspendisse vestibulum, ligula ac interdum suscipit, nulla dui varius metus, vitae mollis odio odio ac neque. Curabitur hendrerit enim lectus, a volutpat nisi blandit non. Fusce nulla risus, iaculis mattis nisi non, iaculis tincidunt elit. Nulla facilisi. Cras varius, orci a mollis elementum, libero ante dignissim nisi, id lacinia tortor nisi tempor nibh. Phasellus iaculis augue eget ligula rhoncus, at ultrices arcu egestas. Curabitur vulputate ornare neque eu suscipit.

Aliquam vel justo ullamcorper, varius dolor at, porttitor enim. Suspendisse lectus ante, condimentum nec ultricies et, vehicula vitae purus. Sed dignissim quis enim non hendrerit. Nam gravida fringilla iaculis. Maecenas feugiat hendrerit rhoncus. Nam congue libero enim, euismod accumsan nunc accumsan at. Curabitur arcu nulla, vehicula ut lorem id, pretium lobortis orci. In pulvinar malesuada nisi, at aliquam erat varius quis. Aenean sodales, lacus et interdum faucibus, dolor ante lobortis turpis, et pellentesque nisi lorem sit amet odio.

Nam eget scelerisque eros. Vivamus consectetur nunc lectus, vitae feugiat massa tempor sed. Integer ullamcorper, est sit amet lobortis dictum, arcu magna tristique orci, nec egestas justo ligula eu justo. Integer in nisi posuere, commodo urna ac, dictum neque. Proin eget ligula arcu. Vestibulum luctus at arcu elementum volutpat. In hac habitasse platea dictumst. Mauris feugiat molestie placerat.

Phasellus posuere accumsan metus, at aliquet felis rhoncus quis. Nam lectus justo, iaculis tincidunt ipsum id, sodales faucibus dui. Fusce dictum dolor ut ligula elementum egestas. Vestibulum eget libero at lorem ornare imperdiet at ac magna. Integer neque purus, sollicitudin vitae ullamcorper ac, consectetur sed eros. Phasellus elementum aliquet felis feugiat pharetra. Donec sit amet nibh at elit ullamcorper volutpat eu a enim. Phasellus interdum augue sed congue pharetra. Aenean tempor arcu nisi, at tempor erat sodales malesuada. Suspendisse eu erat quis arcu mollis egestas. Suspendisse imperdiet commodo dignissim. Fusce sit amet ipsum ligula.

Nam scelerisque tortor mattis nisi convallis, quis pellentesque leo pellentesque. Aliquam placerat, eros sit amet iaculis euismod, erat quam posuere tortor, rhoncus placerat velit nunc eu dolor. Aenean quis nulla velit. Morbi felis arcu, porttitor a eleifend sed, imperdiet non dui. Phasellus ac felis tincidunt, tempor turpis eget, dapibus justo. Integer lectus ligula, pulvinar at fringilla non, rhoncus quis neque. Nam lorem tortor, porttitor sed placerat eget, faucibus a enim. Quisque sit amet rhoncus justo. In finibus metus vitae faucibus pellentesque.

Nam posuere ultricies elementum. Vivamus non rhoncus nisi. Sed id tincidunt odio. Vestibulum non ullamcorper augue. Cras dapibus nisl metus, ut dapibus lorem placerat suscipit. Sed dictum viverra diam, vitae accumsan libero feugiat eu. Pellentesque purus sem, iaculis nec sodales quis, placerat ac orci. Fusce vel massa ultricies, finibus risus eu, interdum nisi. Nam nulla quam, facilisis vitae nulla porta, vulputate imperdiet nulla. Proin vestibulum sollicitudin leo sit amet euismod.

Nunc sit amet laoreet magna. Suspendisse ultrices tortor tortor, sed suscipit massa fringilla eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras cursus condimentum quam. Vestibulum turpis leo, ullamcorper ut odio ut, tempus fermentum ligula. Sed interdum scelerisque neque, sed ullamcorper elit tempus nec. Phasellus feugiat lobortis neque vitae accumsan. Aliquam lorem libero, tincidunt sit amet finibus vitae, vestibulum sit amet nunc. Nulla venenatis fringilla elit ut molestie. Maecenas vel diam convallis, pellentesque elit eu, dictum magna. Phasellus pharetra felis quis porta vehicula. Fusce iaculis tincidunt aliquam. Vestibulum eu lacus eu ligula posuere lacinia.

Sed eleifend augue nec dolor posuere auctor. Fusce luctus venenatis sem ac dictum. Aenean ut convallis augue. Phasellus ornare arcu vitae purus sodales, quis maximus augue hendrerit. Cras auctor lacinia luctus. Nunc et enim aliquet, gravida purus vel, convallis felis. Phasellus libero lacus, efficitur eget lacus a, iaculis pellentesque dui. Curabitur nec molestie purus. In hac habitasse platea dictumst. Phasellus vel tortor ultrices, malesuada purus nec, luctus lorem. Mauris placerat eget elit quis ornare. Integer ante neque, volutpat ac facilisis ac, venenatis et dui. Sed neque libero, laoreet vel ipsum et, pharetra maximus leo. Etiam quis dignissim erat. Praesent vitae nisl turpis.

Aenean quis nibh leo. Fusce sed dolor sed quam dignissim gravida at dapibus odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras dui urna, blandit et neque in, bibendum blandit magna. Curabitur lacinia finibus nisl ut ultricies. Nam pellentesque nisi sed tortor pellentesque, id consectetur odio scelerisque. Morbi non accumsan nunc.

Nunc pellentesque tempus magna, ac pharetra quam gravida non. Quisque in eros nec lorem ullamcorper maximus in id purus. Nulla lobortis ex nibh, sed ornare lacus luctus et. Donec velit dui, condimentum sed tempor vitae, volutpat ut sem. Curabitur nec sollicitudin sapien, ut posuere neque. Suspendisse pulvinar tortor id lacus scelerisque imperdiet. In tempus imperdiet augue non mattis. Sed elementum eleifend efficitur. Maecenas ornare leo libero, quis sollicitudin purus ullamcorper et.

Fusce libero magna, tincidunt a tellus sit amet, iaculis luctus justo. Donec viverra, leo ac mattis cursus, dui dolor varius eros, sit amet sollicitudin enim erat nec ipsum. Proin lectus lacus, volutpat id iaculis ac, posuere at sapien. Proin vitae euismod urna, vel egestas justo. Nam tincidunt tortor nec nibh hendrerit blandit. Ut fringilla commodo hendrerit. Nunc justo arcu, mollis finibus libero at, malesuada feugiat lectus. Aliquam ipsum lectus, commodo quis gravida tristique, interdum id eros. In gravida felis quis rutrum suscipit. In hac habitasse platea dictumst. Phasellus euismod molestie magna eu mattis. Sed magna nulla, auctor accumsan mauris non, varius lobortis odio. Etiam dapibus egestas accumsan. Aenean porttitor enim non lacinia congue. Nunc leo leo, efficitur nec libero sed, finibus tempor lorem.

Etiam suscipit ex vitae lorem lobortis, non malesuada mi aliquam. Vivamus at velit lacinia ipsum fringilla convallis. Donec nibh augue, tempus eu sodales et, egestas non nunc. Suspendisse non convallis velit. Proin viverra volutpat porta. Nulla tristique malesuada odio, id sodales lectus dignissim tristique. In hac habitasse platea dictumst. Sed cursus libero eu turpis semper blandit. Aliquam erat volutpat. Vestibulum ut ex ut elit sollicitudin rutrum laoreet vitae magna. Praesent finibus est a aliquet sagittis. Vivamus nec condimentum nulla. Nunc eu fermentum quam.

Mauris nisi quam, dignissim non tristique a, finibus at diam. Praesent malesuada eu nunc ut bibendum. Fusce a odio lobortis lorem tempor sodales. Nam porttitor feugiat erat ac convallis. Sed sagittis bibendum venenatis. Suspendisse suscipit vel neque quis efficitur. Nam nec efficitur velit. Donec lectus sapien, posuere et lectus a, fermentum sagittis augue. In semper hendrerit orci, sit amet aliquet ante imperdiet vel.

Pellentesque pulvinar lacus id tellus blandit, at commodo ligula condimentum. Mauris sagittis tellus ac mauris viverra faucibus. Vestibulum gravida, arcu ut consequat accumsan, eros metus commodo risus, pharetra tempor dolor nibh vel turpis. Quisque vulputate quis felis vel iaculis. Etiam ac facilisis risus. Donec a risus orci. Aenean imperdiet imperdiet ornare. Quisque non porta magna, et placerat metus. Quisque egestas sapien ac neque iaculis, iaculis dictum tellus scelerisque. Morbi scelerisque mi congue cursus efficitur. Duis eget ligula semper, commodo nibh in, aliquam quam. Curabitur dolor ipsum, facilisis quis purus sed, consectetur porttitor tortor. Fusce mauris magna, tristique et neque ut, scelerisque pretium felis. Nam scelerisque auctor ipsum ut venenatis. Quisque eu urna commodo, gravida enim vel, lobortis eros. Quisque velit purus, tempor vitae mattis et, lacinia vel arcu.

Praesent vel porttitor odio. Nunc risus magna, fringilla ac commodo ut, tempor vel nisi. Donec rhoncus tempus odio, vitae cursus libero dignissim sed. Aenean tristique leo in dui vehicula euismod. Donec ultricies nisl quis velit rhoncus, eget faucibus nibh rutrum. Aenean nec pretium ligula. Duis fermentum laoreet purus, non condimentum velit. Nullam ac odio a mi elementum blandit. Quisque sit amet varius mi. Pellentesque rhoncus egestas mauris sed maximus. Phasellus sapien lectus, volutpat a lectus et, tristique dictum ligula. Phasellus ut elit elit.

In blandit id mauris a suscipit. Vestibulum dignissim ultricies enim, in accumsan urna commodo et. Maecenas in elementum nisl. Maecenas in nisl ullamcorper, vestibulum tellus a, ornare urna. In iaculis lectus non massa euismod, vel tincidunt erat gravida. Mauris lacinia nibh felis, id ornare eros condimentum cursus. Duis sed orci et ante malesuada porta a sit amet tortor. Praesent a risus tellus. Nunc sed pulvinar mi.

Pellentesque et bibendum felis. Fusce lorem sapien, mattis eget facilisis a, vehicula finibus massa. Nullam mattis cursus tristique. Pellentesque tincidunt sagittis imperdiet. Vivamus bibendum gravida varius. Morbi urna purus, convallis quis nunc id, dictum consequat dui. Nam lobortis, metus vel fringilla varius, sapien ligula finibus magna, sed tempus dolor lorem eget enim. In quis enim pharetra, euismod mi sed, maximus est. Aliquam dictum dignissim dictum. Cras in velit erat. Aliquam et turpis tempor, malesuada lectus convallis, laoreet augue. Nam sodales erat purus. Ut ultrices arcu enim, at commodo mauris porta id. Donec sapien eros, venenatis at velit sed, pharetra cursus ex.

Integer quis dui ullamcorper, porta lectus pellentesque, ullamcorper elit. Pellentesque lacinia volutpat nunc vulputate mattis. Pellentesque auctor tellus vel magna aliquet laoreet. Pellentesque dapibus, nisi ac ultricies dictum, velit eros condimentum est, at rhoncus lacus urna et ante. Duis nec iaculis lorem, sit amet lacinia libero. Aenean quis urna eget ante fermentum blandit. Sed vel semper metus, sed tempus mi. Nam laoreet venenatis leo, non accumsan nisl pellentesque ac. Nulla ac lacus odio. Vestibulum semper quis risus id molestie. Suspendisse vestibulum ut est sit amet posuere. Quisque scelerisque nulla sem, nec pulvinar mi condimentum at. Duis sollicitudin ornare mauris in varius.

Morbi scelerisque mi quis dui ultrices venenatis. Nullam pellentesque sem id sapien venenatis, nec tristique lorem laoreet. In vel massa sem. Cras at dignissim nulla. Aliquam a elementum turpis. Aliquam a ipsum eget neque dapibus blandit vitae ac ligula. Nunc odio lorem, consequat sed sapien eu, pharetra vulputate diam. Sed a accumsan metus. Ut molestie tellus ac risus accumsan porttitor at non dolor. Etiam nibh nisl, sollicitudin eget dignissim ultricies, elementum eget tortor. Integer non suscipit tellus. Curabitur eu purus tincidunt, cursus sem in, vehicula metus. Phasellus quam risus, tempor at egestas id, consectetur at massa. Aenean eget dui quam. Aenean mi lacus, laoreet eget tincidunt at, accumsan ac eros.

Aliquam id consequat enim, et pellentesque est. Curabitur tincidunt porta nunc ac finibus. Sed feugiat fringilla finibus. Aliquam purus elit, pellentesque luctus orci non, interdum accumsan diam. Donec eget nunc sed ex ullamcorper posuere. Aliquam posuere varius purus non ullamcorper. Aenean ac risus vel est varius fringilla. Morbi pellentesque lectus id mi consequat hendrerit. Sed eget sapien sed mauris viverra cursus. Suspendisse potenti. Integer sit amet nisl ac velit volutpat imperdiet vitae et justo. Maecenas sed ipsum scelerisque, vestibulum erat id, rutrum ipsum. Duis porttitor eros leo, at mattis sem vulputate quis. Sed sed nulla purus. Praesent vehicula lacinia odio non blandit.

Aenean sed nunc facilisis, venenatis odio vel, aliquet arcu. Maecenas ut mi nulla. Morbi auctor, neque at efficitur lacinia, mauris ligula consectetur leo, vitae hendrerit sapien odio eget mi. Quisque vel tincidunt lectus, ac tristique massa. In placerat lorem non massa vehicula laoreet. Fusce sem metus, accumsan vel ligula id, interdum laoreet urna. Aenean vestibulum odio ut mi ultricies, et feugiat ex maximus. Mauris non egestas lacus. Nulla cursus faucibus scelerisque. Nulla facilisi. Etiam pharetra ante quis fermentum consequat. Vestibulum ullamcorper enim tempor lorem interdum mattis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce malesuada ligula ipsum, et suscipit dolor euismod non. Etiam id ipsum quam.

Mauris pharetra nisi ac arcu sodales vehicula. Fusce posuere quam varius est elementum ultricies. Phasellus hendrerit magna sed eleifend commodo. Morbi rutrum, diam quis tincidunt rutrum, justo libero egestas tellus, eu dignissim dolor urna id sem. Curabitur molestie felis sit amet tellus gravida, quis mattis mauris lacinia. Donec efficitur tortor nec eros efficitur, eget mattis arcu fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam et velit nisi. Duis id nisi quis sem pulvinar rutrum eu eu ante. Quisque dictum neque nec risus facilisis, vitae faucibus mauris ultricies. Donec ullamcorper erat in elementum pretium. Nam pretium et orci eget pretium. Sed luctus metus eget purus ultrices auctor. Nullam aliquet suscipit enim eget vehicula.

Maecenas vulputate massa sit amet ante cursus laoreet. Phasellus justo metus, mollis a blandit a, pulvinar sed quam. Maecenas faucibus, nisl quis ultrices faucibus, mi enim eleifend neque, et efficitur lectus purus et mi. Vivamus in leo aliquet, molestie nibh nec, scelerisque risus. Sed nulla neque, posuere ac sagittis finibus, porta eu ipsum. Sed erat massa, ornare vitae mi at, volutpat ullamcorper tellus. Sed quis sapien sed quam dictum suscipit eu sit amet tortor. Fusce aliquet arcu mauris, vitae malesuada massa porttitor eget. Phasellus fringilla tincidunt felis, sed placerat purus interdum at. Ut ac laoreet nisl. Nullam sed varius tortor, ac rhoncus ligula. Quisque sit amet gravida massa, sed sodales justo. Nullam pellentesque ligula eget lorem tincidunt posuere. Quisque condimentum ante a lacus aliquam laoreet.

Donec placerat tortor commodo eleifend maximus. Mauris a mi eu erat rutrum sollicitudin eget ac urna. Integer at diam ut sem consectetur pharetra vel et dolor. Vestibulum lacinia dolor quis quam ornare, tincidunt mollis lacus laoreet. Suspendisse potenti. Suspendisse ut risus vehicula, scelerisque mauris et, commodo enim. Nunc volutpat augue vel mauris imperdiet dignissim. Suspendisse interdum dui a nunc gravida, et tincidunt diam volutpat. Vestibulum ullamcorper enim ac lacus rutrum sollicitudin. Nunc elementum posuere velit. Vestibulum cursus vel tortor vel aliquam. Phasellus condimentum metus sem, dignissim luctus urna consectetur vel. Maecenas at erat suscipit, fermentum nunc ac, gravida enim. Pellentesque tincidunt rhoncus orci, sit amet cursus mi. Etiam luctus ante ligula, placerat condimentum ipsum pulvinar quis. Integer ipsum turpis, laoreet eu pretium sed, molestie in arcu.

Nulla facilisi. Fusce porta ut libero eget laoreet. Duis ante nibh, maximus ut rhoncus eget, convallis ac urna. Aliquam viverra quam non ligula congue viverra. Praesent congue lacinia nulla, consectetur viverra lorem condimentum sed. Cras tempor quam nec sagittis finibus. Maecenas neque libero, imperdiet vitae tristique eget, pretium in magna. Aliquam ultrices nulla at ante placerat scelerisque. Nam lacinia venenatis lacus eget lacinia. Curabitur facilisis nulla risus, sit amet vestibulum purus fermentum sed. Etiam tempor felis eget nisl luctus elementum. Donec aliquet non neque id viverra.

Nunc eleifend gravida risus, vitae pellentesque orci congue quis. Nulla ullamcorper consequat tellus ac blandit. Mauris dignissim tellus eu purus imperdiet lacinia. Aenean elementum, nunc ac ultricies efficitur, neque lectus posuere nibh, sed hendrerit risus arcu et est. Etiam volutpat, felis eu laoreet porttitor, arcu dolor viverra urna, id hendrerit quam velit ut dolor. Maecenas ut auctor ex. Sed facilisis faucibus pulvinar. Cras in purus id ipsum pharetra mattis vel non sem. Suspendisse auctor pretium ipsum non vehicula. Integer faucibus, ex sit amet gravida interdum, lorem est tristique nulla, id cursus sem dui vel lacus. Morbi non felis blandit, vehicula velit eu, lobortis lectus. Morbi scelerisque ultrices sagittis. Nullam ornare ultrices ante dictum ultricies. Aliquam quam felis, commodo sed dolor vitae, fringilla convallis augue. Ut vitae consectetur purus. Suspendisse et libero vel ligula volutpat convallis.

Sed sed blandit augue. Ut pretium iaculis leo, quis feugiat dui luctus eu. Maecenas vel dui sagittis, scelerisque purus at, posuere nunc. Vivamus accumsan purus justo, id sollicitudin libero posuere ac. Sed vitae blandit ipsum, nec viverra mi. Nunc non cursus enim, non blandit mi. Nam vehicula dolor ac elementum tincidunt. Maecenas mollis ornare viverra. Praesent posuere vel nisl at dignissim. Vestibulum consectetur malesuada bibendum. Integer nec lacus a tortor rhoncus aliquet at non ipsum. Integer eu varius ante, eu mattis magna. Duis at sollicitudin lectus, et volutpat lacus. Praesent enim magna, fringilla id aliquet ac, egestas tincidunt orci. Sed tincidunt sit amet arcu vel scelerisque.

Donec eu venenatis elit. Proin porttitor, mauris mattis tincidunt vulputate, magna ex molestie sem, et pretium nisl tortor sed diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus urna turpis, dapibus at interdum sed, ultrices faucibus nisl. Integer efficitur sapien vel nisi aliquet, ut vulputate sapien aliquet. Etiam vel ligula ac justo porta imperdiet ut a orci. Ut at neque sit amet sem varius eleifend. Sed placerat molestie quam, ut egestas augue pellentesque nec.

Etiam nec vehicula nisl. Fusce maximus purus eget rutrum vulputate. Pellentesque viverra leo ac risus mattis aliquam. Phasellus placerat iaculis risus, et hendrerit augue ornare quis. Vivamus volutpat orci vel aliquam eleifend. Phasellus lobortis libero quam, in finibus ante sodales at. Fusce sit amet velit ac sem efficitur rutrum at sagittis mi. Nullam convallis ligula sit amet mauris interdum tristique. Sed lobortis, nulla vulputate egestas suscipit, magna mauris ullamcorper tortor, eget euismod urna metus ut ante. Proin sed vehicula risus. Maecenas vehicula vehicula libero, sit amet laoreet arcu aliquet at. Nam et volutpat orci. Suspendisse finibus ullamcorper maximus. In hac habitasse platea dictumst. Curabitur nibh eros, ultricies quis sem nec, vehicula dictum tellus.

Pellentesque vestibulum urna felis, ac auctor urna blandit id. Donec vitae eros velit. Nam venenatis fringilla ex, in rhoncus urna vehicula sit amet. Vivamus bibendum leo sit amet tellus feugiat semper. Ut sagittis ipsum eros, nec maximus augue accumsan vel. Aliquam lacus turpis, sodales eget sem a, ultrices porttitor ex. Proin feugiat massa iaculis, dapibus ipsum ac, semper nisi.

Integer ullamcorper auctor neque. Integer egestas condimentum urna, id mollis ex dignissim id. Sed ante ipsum, egestas ut congue ut, sollicitudin congue enim. Donec finibus eros eget lectus feugiat, vitae porttitor dolor tincidunt. Aenean viverra semper ex sed commodo. Vivamus vitae accumsan nunc. Pellentesque orci ante, euismod sit amet consequat eu, accumsan et purus. Nullam egestas euismod orci. Quisque congue, odio a fermentum facilisis, leo sapien euismod mauris, non venenatis mauris felis non neque.

Nullam eu dui et elit elementum suscipit eget ac arcu. Cras sed ex eget sapien tempus placerat sit amet nec velit. Cras eget rhoncus ex. Aenean eu congue nisl. Nam ex est, interdum in pellentesque vitae, tincidunt sed urna. Nulla feugiat commodo arcu. Cras ut ornare tortor, vestibulum dictum velit. Nam vestibulum viverra pretium. Quisque ullamcorper egestas sapien id tristique. Integer commodo tempor dui vel pulvinar. Nullam mollis, diam sed volutpat bibendum, sem urna finibus mi, vel gravida urna erat non massa. Duis ullamcorper, massa quis congue egestas, orci nisi placerat ante, in maximus lectus purus quis neque. Suspendisse elementum ligula mattis, rutrum nibh in, dapibus ligula.
"""
time.sleep(10) # 3 second gap to avoid unwanted actions
kbd.write(string,1.8) # 0.1 second typewrite effect